import Header from '@/components/layout/header'
import './globals.css'

export const metadata = {
  title: 'Nicola Ostler - Fitness Coach',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
